package gaia;

public enum TokenType {
    VARIABLE, LPAREN, RPAREN, TYPE, IDENTIFIER, ASSIGN, NUMBER , STRING,
    IF, ELSE, LBRACE, RBRACE, DOT, PRINT, SEMICOLON,
    EOF,
    PLUS, MINUS, MUL, DIV, EQ, NEQ, LT, GT, LTE, GTE
}
