package VerbosePlusPlus;

public enum TokenType {
    INT, LONG, FLOAT, DOUBLE, STRING_TYPE, CHARACTER,
    INT_LITERAL, LONG_LITERAL, FLOAT_LITERAL, DOUBLE_LITERAL, STRING_LITERAL, CHAR_LITERAL,
    VARIABLE, LPAREN, RPAREN, IDENTIFIER, ASSIGN, NUMBER ,
    IF, ELSE, LBRACE, RBRACE, DOT, SEMICOLON, FOR,
    EOF,
    PLUS, MINUS, MUL, DIV, EQ, NEQ, LT, GT, LTE, GTE
}
