package VerbosePlusPlus;

public enum TokenType {
    VARIABLE, LPAREN, RPAREN, IDENTIFIER, ASSIGN, NUMBER , STRING,
    IF, ELSE, LBRACE, RBRACE, DOT, SEMICOLON, FOR,
    EOF,
    PLUS, MINUS, MUL, DIV, EQ, NEQ, LT, GT, LTE, GTE
}
